"use client";
import { useState } from "react";
import { Play, PenLine, ArrowRight, PackagePlus, ChartNoAxesCombined, Warehouse } from "lucide-react";
import { Chip, TruthAxisLabels, WorldLabel, resultAxes, type TruthAxes } from "@/components/labels";
import { apiRequest, ApiError, Button, ActionStatus, EmptyState, LoadError, Skeleton, useApi, useApiAction } from "@/components/shell";
import { formatDate } from "@/components/pulse/format";
import type { FeedResponse, Labelled } from "@/components/pulse/types";
import styles from "./feed.module.css";
const kinds: Record<string,string> = { sales_day: "Продажи за день", stock_snapshot: "Снимок остатков", in_transit_update: "Товары в пути", price_update: "Изменение цены", judge_message: "Событие судьи", supplier_reply: "Ответ поставщика" };
export function WorldFeed() {
  const feed = useApi<FeedResponse>("/api/world/feed"); const play = useApiAction(); const compose = useApiAction();
  const [receiptAxes, setReceiptAxes] = useState<TruthAxes>({});
  const [playAxes, setPlayAxes] = useState<TruthAxes>({});
  const [quantity, setQuantity] = useState("");
  const [expanded, setExpanded] = useState(false); const [kind, setKind] = useState("judge_message"); const [code, setCode] = useState(""); const [text, setText] = useState("");
  const events = feed.data?.rows ?? feed.data?.events ?? []; const upcoming = events.filter(row => row.state === "scripted").slice(0,3); const shown = upcoming.length ? upcoming : events.slice(0,3);
  return <section className={styles.panel} id="world-feed" aria-labelledby="feed-title"><div className={styles.head}><div><h2 id="feed-title">Лента событий</h2><p className={styles.meta}>Мир меняется. Агенты пересчитывают потребность.</p></div><WorldLabel /></div>
    {feed.error && <LoadError message={feed.data ? "Не удалось обновить ленту — показываю последнее." : feed.error.message} retry={feed.reload} />}
    <div className={styles.events}>{feed.loading ? <Skeleton lines={3} /> : shown.length ? <ol>{shown.map(event => { const Icon = event.kind === "sales_day" ? ChartNoAxesCombined : event.kind === "stock_snapshot" ? Warehouse : PackagePlus; return <li key={event.id}><Icon size={18} /><div><p>{event.text || kinds[event.kind] || event.kind}</p><div className={styles.eventMeta}><span>{kinds[event.kind] ?? "Событие"}</span>{event.actor_id && <span>{event.actor_id}</span>}<time dateTime={event.at}>{formatDate(event.at)}</time>{event.state !== "scripted" && <Chip tone={event.state === "failed" ? "danger" : "neutral"}>{({ processed: "обработано", replayed: "уже обработано — без эффекта", pending: "ждёт обработки", failed: "ошибка обработки" } as Record<string,string>)[event.state] ?? event.state}</Chip>}</div><TruthAxisLabels axes={resultAxes(event)} /></div>{event.state === "scripted" && <span className={styles.next}>Далее <ArrowRight size={14} /></span>}</li>; })}</ol> : !feed.error && <EmptyState>Следующих событий нет — сочините событие для расчёта.</EmptyState>}</div>
    <div className={styles.actions}><Button busy={play.busy} onClick={async () => { const result = await play.run(() => apiRequest<Labelled & { processed: number; replayed?: boolean; emitted?: { state?: string }[] }>("/api/world/play", { method: "POST", body: JSON.stringify({ steps: 1 }) }), result => { if (result.emitted?.some(event => event.state === "failed")) { feed.reload(); throw new ApiError(422, "worker_failed", "Событие получено, но обработка завершилась ошибкой. Требуется проверка."); } return result.replayed ? "Уже обработано — без эффекта" : result.processed === 0 ? "Новых обработанных событий: 0." : `✓ Обработано событий: ${result.processed}`; }); if (result) setPlayAxes(resultAxes(result)); }}><Play size={16} />Воспроизвести</Button><Button aria-expanded={expanded} aria-controls="world-compose" onClick={() => setExpanded(value => !value)}><PenLine size={16} />Сочинить событие</Button></div><ActionStatus error={play.error} receipt={play.receipt} />{play.receipt && <TruthAxisLabels axes={playAxes} />}
    {expanded && <form className={styles.compose} id="world-compose" onSubmit={async e => { e.preventDefault(); const result = await compose.run(() => apiRequest<Labelled & { replayed?: boolean; event?: Labelled & { id: string; state?: string }; run_id?: string }>("/api/world/compose", { method: "POST", body: JSON.stringify({ kind, ...(code.trim() ? { code_1c: code.trim() } : {}), text: text.trim(), payload: { code_1c: code.trim(), ...(kind === "in_transit_update" ? { delta: quantity } : kind === "price_update" ? { unit_cost: quantity, currency: "KZT" } : { qty: quantity, doc_type: "Расходная накладная" }) } }) }), result => { if (result.event?.state === "failed") { feed.reload(); throw new ApiError(422, "worker_failed", "Событие сохранено, но обработка завершилась ошибкой. Требуется проверка."); } return result.replayed ? "Уже обработано — без эффекта" : (result.event ? "✓ Событие сохранено. Результат обработки появится в журнале." : "Запрос принят. Статус события ещё не получен."); }); if (result) setReceiptAxes(resultAxes(result.event ?? result)); }} aria-busy={compose.busy}>
      <div className={styles.fields}><label>Тип события<select value={kind} onChange={e => setKind(e.target.value)} disabled={compose.busy}><option value="judge_message">Событие судьи</option><option value="in_transit_update">Товары в пути</option><option value="price_update">Изменение цены</option></select></label><label>Код 1С<input required value={code} onChange={e => setCode(e.target.value)} placeholder="Код товара" disabled={compose.busy} /></label></div>
      <label>{kind === "price_update" ? "Цена, ₸" : kind === "in_transit_update" ? "Изменение количества, шт" : "Количество, шт"}<input required type="number" inputMode="decimal" min={kind === "in_transit_update" ? undefined : kind === "price_update" ? "0.01" : "1"} step={kind === "price_update" ? "0.01" : "1"} value={quantity} onChange={e => setQuantity(e.target.value)} disabled={compose.busy} /></label>
      <label>Что изменилось?<textarea required maxLength={4000} value={text} onChange={e => setText(e.target.value)} placeholder="Например: Разовый заказ 5 000 шт по коду …" rows={3} disabled={compose.busy} /></label><div className={styles.presets}><button type="button" onClick={() => { setKind("judge_message"); setQuantity("5000"); setText(`Разовый заказ 5 000 шт по коду ${code || "…"}`); }}>Разовый заказ</button><button type="button" onClick={() => { setKind("in_transit_update"); setQuantity("100"); setText(`Товар в пути +100 по коду ${code || "…"}`); }}>В пути +100</button></div><Button busy={compose.busy} type="submit">Добавить событие</Button><ActionStatus error={compose.error} receipt={compose.receipt} />{compose.receipt && <TruthAxisLabels axes={receiptAxes} />}
    </form>}
  </section>;
}
