"use client";
import { useState } from "react";
import { Play, PenLine, ArrowRight, PackagePlus, ChartNoAxesCombined, Warehouse } from "lucide-react";
import { Chip, TruthAxisLabels, WorldLabel, type TruthAxes } from "@/components/labels";
import { apiRequest, Button, ActionStatus, EmptyState, LoadError, Skeleton, useApi, useApiAction } from "@/components/shell";
import { formatDate } from "@/components/pulse/format";
import type { FeedResponse } from "@/components/pulse/types";
import styles from "./feed.module.css";
const kinds: Record<string,string> = { sales_day: "Продажи за день", stock_snapshot: "Снимок остатков", in_transit_update: "Товары в пути", price_update: "Изменение цены", judge_message: "Событие судьи", supplier_reply: "Ответ поставщика" };
export function WorldFeed({ axes }: { axes?: TruthAxes }) {
  const feed = useApi<FeedResponse>("/api/world/feed"); const play = useApiAction(); const compose = useApiAction();
  const [expanded, setExpanded] = useState(false); const [kind, setKind] = useState("judge_message"); const [code, setCode] = useState(""); const [text, setText] = useState("");
  const events = feed.data?.events ?? []; const upcoming = events.filter(row => row.state === "scripted").slice(0,3); const shown = upcoming.length ? upcoming : events.slice(0,3);
  return <section className={styles.panel} id="world-feed" aria-labelledby="feed-title"><div className={styles.head}><div><h2 id="feed-title">Лента событий</h2><p className={styles.meta}>Мир меняется. Агенты пересчитывают потребность.</p></div><WorldLabel /></div>
    {feed.error && <LoadError message={feed.data ? "Не удалось обновить ленту — показываю последнее." : feed.error.message} retry={feed.reload} />}
    <div className={styles.events}>{feed.loading ? <Skeleton lines={3} /> : shown.length ? <ol>{shown.map(event => { const Icon = event.kind === "sales_day" ? ChartNoAxesCombined : event.kind === "stock_snapshot" ? Warehouse : PackagePlus; return <li key={event.id}><Icon size={18} /><div><p>{event.text || kinds[event.kind] || event.kind}</p><div className={styles.eventMeta}><span>{kinds[event.kind] ?? "Событие"}</span>{event.actor_id && <span>{event.actor_id}</span>}<time dateTime={event.at}>{formatDate(event.at)}</time>{event.state !== "scripted" && <Chip tone={event.state === "failed" ? "danger" : "neutral"}>{({ processed: "обработано", replayed: "уже обработано — без эффекта", pending: "ждёт обработки", failed: "ошибка обработки" } as Record<string,string>)[event.state] ?? event.state}</Chip>}</div></div>{event.state === "scripted" && <span className={styles.next}>Далее <ArrowRight size={14} /></span>}</li>; })}</ol> : !feed.error && <EmptyState>Следующих событий нет — сочините событие для расчёта.</EmptyState>}</div>
    <div className={styles.actions}><Button busy={play.busy} onClick={() => play.run(() => apiRequest<{ processed: number; replayed?: boolean; emitted?: unknown[] }>("/api/world/play", { method: "POST", body: JSON.stringify({ steps: 1 }) }), result => result.replayed ? "Уже обработано — без эффекта" : result.processed === 0 ? "Нет новых событий для обработки." : `✓ Обработано событий: ${result.processed}`)}><Play size={16} />Воспроизвести</Button><Button aria-expanded={expanded} aria-controls="world-compose" onClick={() => setExpanded(value => !value)}><PenLine size={16} />Сочинить событие</Button></div><ActionStatus error={play.error} receipt={play.receipt} />
    {expanded && <form className={styles.compose} id="world-compose" onSubmit={async e => { e.preventDefault(); await compose.run(() => apiRequest<{ replayed?: boolean; event?: { id: string }; run_id?: string }>("/api/world/compose", { method: "POST", body: JSON.stringify({ kind, ...(code.trim() ? { code_1c: code.trim() } : {}), text: text.trim() }) }), result => result.replayed ? "Уже обработано — без эффекта" : `✓ Событие сохранено${result.run_id ? ", расчёт выполнен" : " и ожидает обработки"}.`); }} aria-busy={compose.busy}>
      <div className={styles.fields}><label>Тип события<select value={kind} onChange={e => setKind(e.target.value)} disabled={compose.busy}><option value="judge_message">Событие судьи</option><option value="in_transit_update">Товары в пути</option><option value="stock_snapshot">Снимок остатков</option><option value="sales_day">Продажи за день</option><option value="price_update">Изменение цены</option></select></label><label>Код 1С<input value={code} onChange={e => setCode(e.target.value)} placeholder="Код товара" disabled={compose.busy} /></label></div>
      <label>Что изменилось?<textarea required maxLength={4000} value={text} onChange={e => setText(e.target.value)} placeholder="Например: Разовый заказ 5 000 шт по коду …" rows={3} disabled={compose.busy} /></label><div className={styles.presets}><button type="button" onClick={() => { setKind("judge_message"); setText(`Разовый заказ 5 000 шт по коду ${code || "…"}`); }}>Разовый заказ</button><button type="button" onClick={() => { setKind("in_transit_update"); setText(`Товар в пути +100 по коду ${code || "…"}`); }}>В пути +100</button></div><Button busy={compose.busy} type="submit">Добавить событие</Button><ActionStatus error={compose.error} receipt={compose.receipt} />{compose.receipt && <TruthAxisLabels axes={{ ...axes, provenance: "synthetic", external: "local_simulator" }} />}
    </form>}
  </section>;
}
