import Link from "next/link";
import { Check, AlertCircle } from "lucide-react";
import { AgentsLabel, Chip, TruthAxisLabels, resultAxes, type TruthAxes } from "@/components/labels";
import { EmptyState, LoadError, Skeleton, type ApiError } from "@/components/shell";
import { formatTime } from "./format";
import { Sources } from "./Sources";
import type { LedgerResponse, TodayResponse } from "./types";
import styles from "./pulse.module.css";
export function AgentLedger({ data, loading, error, reload, axes, background }: { data?: LedgerResponse; loading: boolean; error: ApiError | null; reload: () => void; axes?: TruthAxes; background?: TodayResponse["background"] }) {
  const rows = data?.rows ?? data?.actions ?? data?.items ?? [];
  return <aside className={styles.workRail} aria-label="Работа агентов"><section className={styles.panel}><div className={styles.sectionHead}><h2>Агенты сделали</h2></div><p className={styles.meta}>Расчёты, изменения и исключённые аномалии</p><div className={styles.ledgerLabels}><AgentsLabel />{data?.stats && <Chip title="Агенты — автоматические действия; вы — действия, требующие вашего решения">агенты {data.stats.auto} · вы {data.stats.needs_you}</Chip>}{!data?.stats && !loading && <Chip>Статистика пока недоступна</Chip>}</div>
    {error && <LoadError message={data ? "Не удалось обновить журнал — показываю последнее." : error.message} retry={reload} />}{loading ? <Skeleton lines={6} /> : rows.length ? <ol className={styles.ledger}>{rows.slice(0,8).map(row => <li key={row.id}><div className={styles.ledgerSummary}>{row.result === "failed" ? <AlertCircle size={16} /> : <Check size={16} />}<p>{row.summary_ru}</p></div><div className={styles.ledgerMeta}><time dateTime={row.at}>{formatTime(row.at)}</time><Chip tone={row.result === "failed" ? "danger" : row.autonomy === "escalated" ? "warning" : "neutral"}>{row.result === "failed" ? "ошибка" : row.autonomy === "auto" ? "автоматически" : "ждёт вас"}</Chip></div><details className={styles.why}><summary>Почему?</summary><p>{row.rationale_ru || "Обоснование не указано в журнале."}</p><Sources sources={row.sources} /><TruthAxisLabels axes={Object.values(resultAxes(row)).some(Boolean) ? resultAxes(row) : axes} />{row.code_1c && <Link className={styles.inlineLink} href={`/skus/${encodeURIComponent(row.code_1c)}`}>Код 1С: {row.code_1c}</Link>}{row.po_id && <Link className={styles.inlineLink} href={`/orders/${encodeURIComponent(row.po_id)}`}>Открыть заказ</Link>}</details></li>)}</ol> : !error && <EmptyState>Пока нет выполненных действий. Здесь будет видно, что агенты рассчитали и почему.</EmptyState>}
    </section><section className={styles.background}><h2>Фоновая работа</h2>{background?.length ? <ul>{background.map((row,index) => <li key={typeof row === "string" ? index : row.id ?? index}>{typeof row === "string" ? row : <><p>{row.title ?? row.summary_ru}</p>{row.at && <span className={styles.meta}>Последнее событие · {formatTime(row.at)}</span>}{row.next_check_at && <span className={styles.meta}>Следующая проверка · {formatTime(row.next_check_at)}</span>}</>}</li>)}</ul> : <p className={styles.meta}>{background ? "Нет активных задач. Новые события появятся в журнале после обработки." : "Статус фоновых задач пока недоступен."}</p>}</section></aside>;
}
