import type { TruthAxes } from "@/components/labels";
import type { Money } from "./format";
export type Axes = { provenance?: TruthAxes["provenance"]; ai?: TruthAxes["ai"]; external?: TruthAxes["external"]; state_version?: number };
export type Urgency = "critical" | "soon" | "normal" | "none";
export type OneOff = { doc_no: string | null; ym: string; qty: number; threshold: number };
export type TransitSource = { po_ref: string; qty: string; expected_at: string | null; source_file?: string | null };
export type Components = {
  source_months?: number; sales_lines?: number; stock_month?: string; stock_stale?: boolean; transit_rows?: number;
  base_rate?: number; season_source?: "sku" | "supplier" | string; season?: Record<string, number>; growth?: number; horizon_days?: number;
  forecast_qty?: number; monthly_forecast?: Record<string, number>; stockout_months?: string[]; stockout_uplift?: number;
  outliers_excluded?: OneOff[]; median_month_qty?: number; p95_doc_qty?: number; outlier_threshold?: number; safety?: number;
  on_hand?: number; on_hand_as_of?: string; in_transit?: number; in_transit_sources?: TransitSource[]; net_need?: number; raw_need?: number;
  moq?: number; urgency?: Urgency; raw_observed_forecast?: number; days_of_cover?: number;
};
export type RecRow = { id: string; code_1c: string; name: string; on_hand: string; in_transit: string; forecast_qty: string; qty_recommended: number; qty_adjusted: number | null; moq: number; urgency: Urgency; rationale_ru: string; components: Components; outliers_excluded: OneOff[]; stockout_months: string[]; version?: number };
export type RecGroup = { supplier_id: string; total_qty: number; total_cost: Money | null; cost_known_lines: number; rows: RecRow[] };
export type RecResponse = Axes & { groups: RecGroup[] };
export type Sku = { code_1c: string; supplier_id: string; article: string | null; name: string; unit: string | null; category: string | null; unit_cost: string | null; moq: number; first_sale_ym?: string | null; months_with_sales?: number | null; median_month_qty?: string | null; p95_doc_qty?: string | null; on_hand_qty?: string | null; on_hand_as_of?: string | null; version: number; supplier_name?: string; currency?: string };
export type SkuList = Axes & { items: Sku[]; total: number };
export type SeriesPoint = { ym: string; qty_file: string | null; qty_lines: string | null; qty_regular: string | null; stockout: number; stock: string | null; stock_known: boolean; outliers: Array<{ doc_no?: string | null; qty?: string | number; at?: string | null; decision?: string; state?: string }> };
export type Forecast = { id: string; run_id: string; horizon_months: number; base_rate: string; season: Record<string, number>; growth: string; stockout_uplift: string; safety: string; method_ru?: string | null; version: number };
export type SkuRecommendation = { id: string; run_id: string; code_1c: string; supplier_id: string; qty_recommended: number; qty_adjusted: number | null; on_hand: string; in_transit: string; urgency: Urgency; rationale_ru: string; components: Components; state: string; proposal_id: string | null; version: number };
export type TimelineRow = { id: string; kind: string; summary_ru: string; rationale_ru?: string | null; autonomy?: string; result?: string; at: string; run_id?: string };
export type InTransitRow = { id: number; code_1c: string; po_ref: string; qty: string; expected_at: string | null; source_file?: string | null };
export type SkuResponse = Axes & { sku: Sku; series: SeriesPoint[]; forecast?: Forecast | null; recommendation?: SkuRecommendation | null; in_transit: InTransitRow[]; timeline: TimelineRow[] };
export type QueueItem = { id: string; kind: "proposal" | "task" | string; title: string; why: string; sources: string[]; money_at_stake?: Money | null; options: Array<{ key: string; label: string; effect: string }>; href: string; since: string };
export type QueueResponse = Axes & { items: QueueItem[]; empty_reason?: string };
export type RiskTop = { code_1c: string; name: string; days_of_cover: number; lead_time_days: number; urgency?: Urgency };
export type MoneyView = { cash: Money[]; committed_by_supplier: Array<{ supplier_id: string; amount: string; currency: string; lines: number; cost_known_lines: number }>; next_60d: { out: Array<{ at: string; amount: string; currency: string; po_id: string; kind: string }> }; stock_value: (Money & { cost_known_share?: number; cost_unknown_count?: number }) | null; risks: Array<{ code: string; count: number; label_ru: string }> };
export type TodayResponse = Axes & { lead: string; decision: QueueItem | null; queue_count: number; pulse: { money: MoneyView; stockout_risk: { count: number; top: RiskTop[] }; agents: { auto: number; needs_you: number; ratio: number } }; commitments: Array<{ id: string; kind: string; title: string; next_event?: string | null; amount?: Money | null; owner?: string; state?: string }>; background: Array<{ id: string; summary_ru: string; at: string }>; feed_next: unknown[]; empty_reason?: string };
export type LedgerRow = { id: string; run_id: string; kind: string; code_1c: string | null; po_id: string | null; subject_ref: string | null; summary_ru: string; rationale_ru: string | null; sources: unknown[]; autonomy: string; result: string; provider: string | null; at: string };
export type LedgerResponse = Axes & { rows: LedgerRow[]; stats: { auto: number; needs_you: number } };
export type MoneyResponse = Axes & MoneyView;
export type ProposalDetail = Axes & { proposal: { id: string; kind: string; version: number; state: string; subject_id: string | null; money_at_stake: Money | null; payload: { lines?: Array<{ code_1c: string; name: string; qty: number; unit_cost: string | null }>; cost_known_lines?: number } } };
