-- Ainalym schema v0 (root, T+8) — additive changes only (new columns/tables/indexes; never a rename)
PRAGMA journal_mode = WAL;
CREATE TABLE IF NOT EXISTS organization (id TEXT PRIMARY KEY, name TEXT NOT NULL, payload TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS supplier (id TEXT PRIMARY KEY, name TEXT NOT NULL, lead_time_days INTEGER NOT NULL, review_days INTEGER NOT NULL DEFAULT 30, terms TEXT NOT NULL DEFAULT '{}', currency TEXT NOT NULL DEFAULT 'KZT', version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS sku (code_1c TEXT PRIMARY KEY, supplier_id TEXT NOT NULL REFERENCES supplier(id), article TEXT, name TEXT NOT NULL, unit TEXT, category TEXT, unit_cost TEXT, moq INTEGER NOT NULL DEFAULT 1, weight TEXT, first_sale_ym TEXT, months_with_sales INTEGER, median_month_qty TEXT, p95_doc_qty TEXT, on_hand_qty TEXT, on_hand_as_of TEXT, version INTEGER NOT NULL DEFAULT 1);
CREATE INDEX IF NOT EXISTS sku_supplier ON sku(supplier_id, category);
CREATE TABLE IF NOT EXISTS sales_line (id INTEGER PRIMARY KEY AUTOINCREMENT, code_1c TEXT NOT NULL, doc_no TEXT, doc_type TEXT, at TEXT NOT NULL, warehouse TEXT, qty TEXT NOT NULL, source TEXT NOT NULL DEFAULT 'file');
CREATE INDEX IF NOT EXISTS sales_line_code_at ON sales_line(code_1c, at);
CREATE INDEX IF NOT EXISTS sales_line_doc ON sales_line(doc_no);
CREATE TABLE IF NOT EXISTS sales_month (code_1c TEXT NOT NULL, ym TEXT NOT NULL, qty_file TEXT, qty_lines TEXT, qty_regular TEXT, stockout INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (code_1c, ym));
CREATE TABLE IF NOT EXISTS stock_month (code_1c TEXT NOT NULL, ym TEXT NOT NULL, opening_qty TEXT, known INTEGER NOT NULL DEFAULT 1, PRIMARY KEY (code_1c, ym));
CREATE TABLE IF NOT EXISTS in_transit (id INTEGER PRIMARY KEY AUTOINCREMENT, code_1c TEXT NOT NULL, po_ref TEXT NOT NULL, qty TEXT NOT NULL, expected_at TEXT, source_file TEXT);
CREATE INDEX IF NOT EXISTS in_transit_code ON in_transit(code_1c);
CREATE TABLE IF NOT EXISTS seasonality (supplier_id TEXT NOT NULL, year INTEGER NOT NULL, month INTEGER NOT NULL, revenue_kzt TEXT, PRIMARY KEY (supplier_id, year, month));
CREATE TABLE IF NOT EXISTS season_index (supplier_id TEXT NOT NULL, month INTEGER NOT NULL, idx TEXT NOT NULL, PRIMARY KEY (supplier_id, month));
CREATE TABLE IF NOT EXISTS outlier_doc (id INTEGER PRIMARY KEY AUTOINCREMENT, code_1c TEXT NOT NULL, doc_no TEXT, at TEXT, qty TEXT NOT NULL, rule TEXT NOT NULL, stat TEXT NOT NULL DEFAULT '{}', decision TEXT NOT NULL DEFAULT 'auto', state TEXT NOT NULL DEFAULT 'excluded', run_id TEXT);
CREATE INDEX IF NOT EXISTS outlier_code ON outlier_doc(code_1c);
CREATE TABLE IF NOT EXISTS forecast (id TEXT PRIMARY KEY, run_id TEXT NOT NULL, code_1c TEXT NOT NULL, horizon_months REAL NOT NULL, base_rate TEXT NOT NULL, season TEXT NOT NULL DEFAULT '{}', growth TEXT NOT NULL DEFAULT '1', stockout_uplift TEXT NOT NULL DEFAULT '0', safety TEXT NOT NULL DEFAULT '0', method_ru TEXT, version INTEGER NOT NULL DEFAULT 1);
CREATE INDEX IF NOT EXISTS forecast_run ON forecast(run_id, code_1c);
CREATE TABLE IF NOT EXISTS calc_run (id TEXT PRIMARY KEY, org_id TEXT, scope TEXT NOT NULL DEFAULT '{}', params TEXT NOT NULL DEFAULT '{}', started_at TEXT NOT NULL, finished_at TEXT, skus INTEGER NOT NULL DEFAULT 0, recommended INTEGER NOT NULL DEFAULT 0, agent_run_id TEXT);
CREATE INDEX IF NOT EXISTS calc_run_org_started ON calc_run(org_id, started_at DESC);
CREATE TABLE IF NOT EXISTS recommendation (id TEXT PRIMARY KEY, run_id TEXT NOT NULL, code_1c TEXT NOT NULL, supplier_id TEXT NOT NULL, qty_recommended INTEGER NOT NULL, qty_adjusted INTEGER, on_hand TEXT NOT NULL DEFAULT '0', in_transit TEXT NOT NULL DEFAULT '0', forecast_id TEXT, urgency TEXT NOT NULL DEFAULT 'none', rationale_ru TEXT NOT NULL DEFAULT '', components TEXT NOT NULL DEFAULT '{}', state TEXT NOT NULL DEFAULT 'proposed', proposal_id TEXT, version INTEGER NOT NULL DEFAULT 1);
CREATE INDEX IF NOT EXISTS recommendation_run ON recommendation(run_id, supplier_id);
CREATE TABLE IF NOT EXISTS purchase_order (id TEXT PRIMARY KEY, supplier_id TEXT NOT NULL, run_id TEXT, state TEXT NOT NULL DEFAULT 'draft', total_qty INTEGER NOT NULL DEFAULT 0, total_cost TEXT, cost_known_lines INTEGER NOT NULL DEFAULT 0, eta TEXT, export_path TEXT, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS purchase_order_line (id INTEGER PRIMARY KEY AUTOINCREMENT, po_id TEXT NOT NULL REFERENCES purchase_order(id), code_1c TEXT NOT NULL, qty INTEGER NOT NULL, unit_cost TEXT, rationale_ru TEXT);
CREATE INDEX IF NOT EXISTS po_line_po ON purchase_order_line(po_id);
CREATE TABLE IF NOT EXISTS proposal (id TEXT PRIMARY KEY, org_id TEXT, kind TEXT NOT NULL, subject_type TEXT, subject_id TEXT, subject_version INTEGER, payload TEXT NOT NULL DEFAULT '{}', affects TEXT NOT NULL DEFAULT '[]', supersedes_id TEXT, state TEXT NOT NULL DEFAULT 'needs_review', rationale_ru TEXT, sources TEXT NOT NULL DEFAULT '[]', money_at_stake TEXT, version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS proposal_state ON proposal(state, kind);
CREATE INDEX IF NOT EXISTS proposal_org_state_created ON proposal(org_id, state, created_at DESC);
CREATE TABLE IF NOT EXISTS approval (id TEXT PRIMARY KEY, proposal_id TEXT NOT NULL, proposal_version INTEGER NOT NULL, decision TEXT NOT NULL, adjustments TEXT, by TEXT, at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS task (id TEXT PRIMARY KEY, title TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'preparing', owner_role TEXT, proposal_id TEXT, next_event_at TEXT, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS obligation (id TEXT PRIMARY KEY, kind TEXT NOT NULL, po_id TEXT, supplier_id TEXT, amount TEXT NOT NULL, currency TEXT NOT NULL DEFAULT 'KZT', due_at TEXT, state TEXT NOT NULL DEFAULT 'open', basis TEXT, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS payment (id TEXT PRIMARY KEY, direction TEXT NOT NULL, counterparty_id TEXT, amount TEXT NOT NULL, currency TEXT NOT NULL DEFAULT 'KZT', payment_ref TEXT NOT NULL UNIQUE, at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS world_event (id TEXT PRIMARY KEY, org_id TEXT NOT NULL, seq INTEGER, kind TEXT NOT NULL, actor_id TEXT, code_1c TEXT, po_id TEXT, at TEXT, source_id TEXT NOT NULL, text TEXT, payload TEXT NOT NULL DEFAULT '{}', state TEXT NOT NULL DEFAULT 'scripted', run_id TEXT, emitted_at TEXT, processed_at TEXT, UNIQUE (org_id, source_id));
CREATE INDEX IF NOT EXISTS world_event_state ON world_event(state, seq);
CREATE INDEX IF NOT EXISTS world_event_org_state ON world_event(org_id, state, seq);
CREATE INDEX IF NOT EXISTS world_event_code ON world_event(code_1c, state);
CREATE TABLE IF NOT EXISTS agent_run (id TEXT PRIMARY KEY, org_id TEXT NOT NULL, trigger_type TEXT NOT NULL, trigger_ref TEXT, state TEXT NOT NULL DEFAULT 'running', started_at TEXT NOT NULL, finished_at TEXT, actions_count INTEGER NOT NULL DEFAULT 0, escalations_count INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS agent_run_org ON agent_run(org_id, started_at);
CREATE TABLE IF NOT EXISTS agent_action (id TEXT PRIMARY KEY, run_id TEXT NOT NULL, org_id TEXT NOT NULL, world_event_id TEXT, code_1c TEXT, po_id TEXT, kind TEXT NOT NULL, subject_ref TEXT, summary_ru TEXT NOT NULL, rationale_ru TEXT, sources TEXT NOT NULL DEFAULT '[]', autonomy TEXT NOT NULL DEFAULT 'auto', result TEXT NOT NULL DEFAULT 'done', provider TEXT, model_version TEXT, idempotency_key TEXT UNIQUE, at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS agent_action_at ON agent_action(at);
CREATE INDEX IF NOT EXISTS agent_action_code ON agent_action(code_1c);
CREATE INDEX IF NOT EXISTS agent_action_org_at ON agent_action(org_id, at);
CREATE INDEX IF NOT EXISTS agent_action_po ON agent_action(po_id, at);
CREATE TABLE IF NOT EXISTS decision_record (id TEXT PRIMARY KEY, question_id TEXT NOT NULL, subject_ref TEXT, answer TEXT, distribution TEXT NOT NULL DEFAULT '{}', provider TEXT, model_version TEXT, result_state TEXT NOT NULL, mode TEXT NOT NULL, at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ledger_peer_record (id TEXT PRIMARY KEY, peer TEXT NOT NULL, external_identity TEXT NOT NULL, kind TEXT, payload TEXT NOT NULL DEFAULT '{}', version INTEGER NOT NULL DEFAULT 1, state TEXT NOT NULL, as_of TEXT NOT NULL, UNIQUE (peer, external_identity));
CREATE TABLE IF NOT EXISTS state_version (n INTEGER NOT NULL);
INSERT INTO state_version (n) SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM state_version);
