"use client";
import Link from "next/link";
import { ArrowLeft, CalendarDays, AlertTriangle } from "lucide-react";
import { useApi, LoadError, Skeleton, EmptyState } from "@/components/shell";
import { Chip, TruthAxisLabels, resultAxes } from "@/components/labels";
import type { MoneyView } from "@/components/pulse/types";
import { formatDate, formatMoney, sumByCurrency } from "@/components/pulse/format";
import styles from "./money.module.css";
export function MoneyPage({ initial }: { initial?: MoneyView }) {
  const money = useApi<MoneyView>("/api/money", initial); const data = money.data; const ready = Boolean(data && !data.empty_reason);
  const out = data?.next_60d?.out ?? []; const outTotals = sumByCurrency(out); const committed = data?.committed_by_supplier ?? [];
  const groups = new Map<string, typeof out>();
  for (const row of [...out].sort((a,b) => a.at.localeCompare(b.at))) { const day = row.at.slice(0,10); groups.set(day, [...(groups.get(day) ?? []), row]); }
  return <div className={styles.page}><Link className={styles.back} href="/today"><ArrowLeft size={16} />Сегодня</Link><header className={styles.header}><div><h1>Деньги</h1><p>Обязательства поставщикам и ближайшие платежи</p></div><Chip>Горизонт · 60 дней</Chip></header>
    {money.error && <LoadError message={data ? "Не удалось обновить деньги — показываю последнее известное." : money.error.message} retry={money.reload} />}
    {data?.empty_reason && <p className={styles.meta}>Денежный расчёт пока недоступен.</p>}
    <section className={styles.summary} aria-label="Денежные показатели"><div><span>Денег на счёте</span>{money.loading ? <Skeleton lines={2} /> : data?.cash?.length ? data.cash.map(row => <strong key={row.currency}>{formatMoney(row)}</strong>) : <strong className={styles.word}>Остатки не заданы</strong>}<p>По доступным записям</p></div><div><span>К оплате · 60 дней</span>{money.loading ? <Skeleton lines={2} /> : outTotals.length ? outTotals.map(row => <strong key={row.currency}>{formatMoney(row)}</strong>) : <strong className={styles.word}>{ready ? "Не запланировано" : "Нет данных"}</strong>}<p>По утверждённым заказам</p></div><div><span>Стоимость запаса (SE)</span>{money.loading ? <Skeleton lines={2} /> : <strong className={!data?.stock_value ? styles.word : undefined}>{data?.stock_value ? formatMoney(data.stock_value) : "Не рассчитана"}</strong>}<p>{data?.stock_value ? `Стоимость известна для ${new Intl.NumberFormat("ru-RU", { style: "percent", maximumFractionDigits: 1 }).format(data.stock_value.cost_known_share)} товарных позиций` : "IEK: себестоимость не задана"}</p></div></section>
    <div className={styles.columns}><section className={styles.panel}><div className={styles.sectionHead}><h2>График платежей</h2><CalendarDays size={18} /></div><p className={styles.meta}>Предоплата при утверждении и остаток к дате поставки. Каждая валюта отдельно.</p>
      {money.loading ? <Skeleton lines={5} /> : groups.size ? <div className={styles.schedule}>{[...groups].map(([day, rows]) => <section key={day} className={styles.day}><h3><time dateTime={day}>{formatDate(day)}</time></h3><ul>{rows.map((row,index) => <li key={`${row.po_id}-${row.kind}-${index}`}><div><Link href={`/purchases/${encodeURIComponent(row.po_id)}`}>{row.po_id}</Link><p className={styles.meta}>{row.kind === "supplier_prepayment" ? "Предоплата поставщику" : row.kind === "supplier_balance" ? "Остаток к поставке" : "Обязательство поставщику"}</p></div><strong>{formatMoney(row)}</strong></li>)}</ul></section>)}</div> : <EmptyState>{ready ? "На ближайшие 60 дней платежи не запланированы. Обязательства появятся после утверждения заказов." : "График пока недоступен."}</EmptyState>}
    </section><aside className={styles.panel}><div className={styles.sectionHead}><h2>Что требует внимания</h2><AlertTriangle size={18} /></div>{money.loading ? <Skeleton lines={3} /> : data?.risks.length ? <ul className={styles.risks}>{data.risks.map((risk,index) => <li key={typeof risk === "string" ? index : risk.id ?? risk.code ?? index}><p>{typeof risk === "string" ? risk : risk.label_ru ?? risk.title ?? risk.message ?? risk.reason ?? "Риск без описания"}</p>{typeof risk === "object" && risk.count !== undefined && <Chip tone="warning">{risk.count} товаров</Chip>}{typeof risk === "object" && risk.po_id && <Link href={`/purchases/${encodeURIComponent(risk.po_id)}`}>{risk.po_id}</Link>}</li>)}</ul> : <EmptyState>{ready ? "В доступных записях риски не отмечены." : "Риски пока недоступны."}</EmptyState>}<p className={styles.footnote}>Неизвестная себестоимость не считается нулевой. Неполные суммы отмечены отдельно.</p></aside></div>
    <section className={styles.panel} aria-labelledby="supplier-money"><div className={styles.sectionHead}><h2 id="supplier-money">Обязательства по поставщикам</h2><Link href="/purchases">Открыть заказы</Link></div>{money.loading ? <Skeleton lines={3} /> : committed.length ? <div className={styles.tableWrap}><table><thead><tr><th>Поставщик</th><th>Сумма обязательств</th><th>Позиций с известной стоимостью</th><th>Основание</th></tr></thead><tbody>{committed.map(row => <tr key={`${row.supplier_id}-${row.currency}`}><td><Link href={`/purchases?supplier=${encodeURIComponent(row.supplier_id)}`}>{row.supplier_id}</Link></td><td><strong>{row.cost_known_lines === 0 ? "Себестоимость не задана" : formatMoney(row)}</strong>{row.cost_known_lines > 0 && row.cost_known_lines < row.lines && <p className={styles.meta}>Неполная сумма</p>}</td><td>{row.cost_known_lines} из {row.lines}</td><td>Утверждённые заказы</td></tr>)}</tbody></table></div> : <EmptyState>{ready ? "Утверждённых заказов пока нет — денежные обязательства ещё не возникли." : "Обязательства пока недоступны."}</EmptyState>}</section>
    {data && <TruthAxisLabels axes={resultAxes(data)} />}
  </div>;
}
